### ISSUE TITLE
Slow Python API calls, request for I2C protocol

### ISSUE THREAD

**Issue by napratin** [Exadler/DMCC_Library#3]
[We](https://github.com/NCSUhardware/) ran some timing tests using the DMCC Python API, and the results show that each call is taking way too long for it to be usable (e.g., when setting 4 motors on one by one, we need that to happen pretty much instantaneously, but there's a clear delay per motor call). We understand that this is because the entire initialization routine occurs for each Python-to-C call.

Since we need an efficient Python interface to the DMCC capes, we tried to re-implement the library in native Python (see [this fork](https://github.com/NCSUhardware/DMCC_Library)). So far, we haven't been able to make much progress as the protocol between the Beaglebone and the cape is not easily discernible from the code.

@paulctan / @sarahttan: Could you please provide us with the I2C protocol that the cape uses to communicate (i.e. all the different commands along with parameters, byte order etc.)? Also, if there are any other necessary initialization steps, it would be great to know them as well. Needless to say, once we have a stable Python library we'll be glad to contribute it back. Thanks!

**Comment by paulctan** [comment]
Updated I2C communication document can be found here -

[https://docs.google.com/document/d/1vNoH5H8ODUPpGeQgL33aTz3tzo64SsbbzK1ySuSa2As/edit?usp=sharing](url)
